name: pipelines

on:
  push:
    branches:
      -main
  workflow_dispatch:
  
  pull_request: 
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: build frontend
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci
      working-directory: FrontCatalogo

    - name: Build frontend
      run: npm run build
      working-directory: FrontCatalogo

    - name: Install backend dependencies
      run: npm ci
      working-directory: BackCatalogo

    - name: Build backend
      run: npm run devStart
      working-directory: BackCatalogo


  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID}}
        aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY}}
        aws configure set default.region ${{ env.AWS_REGION}}

    - name: Push front-end code to EC2
      run: |
        scp -i ${{ secret.SSHKEY}} ${{ env.CIFIP}}
        cd ~
        touch funciona

#     - name: Push back-end code to EC2
#       run: |
#         scp -i path/to/your/private/key.pem -r path/to/your/backend user@your-ec2-instance-ip:/path/to/destination
