name: pipelines

on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: build frontend
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci
      working-directory: FrontCatalogo

    - name: Build frontend
      run: npm run build
      working-directory: FrontCatalogo

    - name: Install backend dependencies
      run: npm ci
      working-directory: BackCatalogo

    - name: Build backend
      run: npm run devStart
      working-directory: BackCatalogo




# stages:
#     - build
#     - deploy

# build_backend:
#     stage: build
#     image: node:latest    
#     script:
#         - cd BackCatalogo
#         - ls
#         - npm run devStart
#         - echo "Building back-end..."
#         - echo "Finished building the app."
#     artifacts:
#         expire_in: 1 week
#         paths:
#             - BackCatalogo

      
    
    
    

# build_frontend:
#   stage: build
#   image: node:latest
#   script:
#     - echo "Building the app"
#     - cd FrontCatalogo
#     - ls
#     - npm --force install
#     - CI=false npm run build
#     - echo "Finished building the app."
#     - cd dist
#     - ls
#     - cd ..
#     - pwd
#   artifacts:
#     name: react_build
#     paths:
#       - ./FrontCatalogo/dist/
