name: pipelines

on:
  push:
    branches: ["main"]
      
  workflow_dispatch:
  
  pull_request: 
    branches: ["main"]
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci
      working-directory: FrontCatalogo

    - name: Build frontend
      run: npm run build
      working-directory: FrontCatalogo

    - name: Install backend dependencies
      run: npm ci
      working-directory: BackCatalogo

    - name: Install PM2
      run: |
        
        npm install -g pm2
      working-directory: BackCatalogo
      

    - name: Build backend
      run: |
        pwd
        ls
        pm2 start server.js
      working-directory: BackCatalogo


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        aws --version

    - name: Configure AWS credentials
      run: |
        

        echo ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws configure set default.region ${{ secrets.AWS_REGION}}

    - name: Push back-end code to EC2
      run: |
        apk update && apk add openssh-client bash
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        eval $(ssh-agent -s)
        echo "${{ secrets.SSHKEY}}" | tr -d '\r' | ssh-add - 
        touch ~/.ssh/config
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        ssh-keyscan -H ${{ secrets.CIFIP}} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

        echo "Deploy started"
        ssh ubuntu@${{ secrets.CIFIP}}
        sudo su
        ls
        cd ~
        

     
